### ISSUE TITLE
allow url shortening

### ISSUE THREAD

**Issue by bhanderson** [bhanderson/pbnh#1]
look at pb's implementation to see if its good enough

**Comment by jetpacktuxedo** [comment]
Also URL Lengthening, for shiggles

**Comment by jetpacktuxedo** [comment]
The way I designed the db, I intend for you to pass me the url as "data" and set the mime to "redirect" or something similar.

**Comment by bhanderson** [comment]
I set the mime to redirect and catch it on return.
