### ISSUE TITLE
Hashes as IDs?

### ISSUE THREAD

**Issue by jetpacktuxedo** [bhanderson/pbnh#10]
De-duplicate pastes for free

preferably do this git style, where there is a short id and a full id, with the short id going to the most recently accessed full_id with the corresponding short_id

It might make it harder to import old pastes, though

**Comment by bhanderson** [comment]
I think we should just use an incrementer. It's really simple and importing pastes will be easy.

**Comment by jetpacktuxedo** [comment]
Both are crazy easy to do. Both have +s and -s.

Hashes: free de-duplication of pastes, not easily guessable URLs, but might be harder to import from paste/haste

Auto incrementing ID: one less line of code, potentially slightly faster, moves the work to postgres, could have problems if people accidentally upload duplicate copies if very large files (I've done this myself with pictures), more predictable URLs, no possibility of a collision.

If we pull in the concept of "labels" like pb has then we can maintain backwards compatibility with haste/paste by setting the label to the old paste id. Overall I don't think either method has a severe benefit or severe drawback, and I think we can probably decide later.

**Comment by bhanderson** [comment]
por que no los dos. auto index for easy lookup and sha to dedupe and lookup

**Comment by jetpacktuxedo** [comment]
DB is set up for this to work right now. I should figure out how to tell the db to index hashids as well as ids, but the dedupe part is already working, and you can query by either id or hashid. Flask needs routing to handle hash-based lookups.

**Comment by jetpacktuxedo** [comment]
I think you have resolved this on the flask side as well. Maybe needs some testing.

**Comment by bhanderson** [comment]
Will work in what I'm about to push. needs tests though just like everything else lol
