### ISSUE TITLE
Vanity pastes

### ISSUE THREAD

**Issue by jetpacktuxedo** [bhanderson/pbnh#12]
Not sure whether we want to implement this or not.

pb allows naming pastes with a /~something flag. 

https://ptpb.pw/#vanity-pastes

**Comment by bhanderson** [comment]
Should be easy to do if everything has a tilda in front

**Comment by jetpacktuxedo** [comment]
If we are going to do this I should add a "vanity" column to the db

**Comment by bhanderson** [comment]
I dont really want to do this.

**Comment by jetpacktuxedo** [comment]
Lol. Sounds fair enough.
