### ISSUE TITLE
should work from cli easily using curl

### ISSUE THREAD

**Issue by bhanderson** [bhanderson/pbnh#4]
write a cli client using curl

**Comment by jetpacktuxedo** [comment]
See issue #6 
`thing | curl -F c=@- $ADDRESS` is really nice, imo

**Comment by jetpacktuxedo** [comment]
I would go ahead and call this one resolved. We can curl to and from the server and that works fine for smallish pastes. The part that doesn't work is large files, but that is covered by issue #8 .
